name: MichaelPlugin
version: '${project.version}'
main: me.minignomer.michaelplugin.MichaelPlugin
api-version: '1.20'
authors: [MiniGnomer]
commands:
  togglegamemode:
    aliases:
      - g
    permission: michaelplugin.togglegamemode